---

- name: 'Installing'
  hosts: localhost
  connection: local

  become: true
  tasks:

  - block: # Yggdrasil Network
    - name: '[Yggdrasil] Add GPG key'
      apt_key:
        url: https://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/key.txt
        id: 569130E8CA20FBC4CB3FDE555898470A764B32C9
    - name: '[Yggdrasil] Add repository'
      apt_repository:
        repo: deb http://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/ debian yggdrasil
        filename: yggdrasil
        update_cache: no
    - name: '[Yggdrasil] Install'
      apt: update_cache=yes name=yggdrasil
    - name: '[Yggdrasil] Check if config is new'
      lineinfile:
        name: /etc/yggdrasil.conf
        line: '# Maximum Transmission Unit (MTU)'
      check_mode: yes
      register: config_state
    - name: '[Yggdrasil] Clean up `/etc/yggdrasil.conf`'
      shell: sed '/^[[:blank:]]*#/d;s/#.*//' /etc/yggdrasil.conf | tee /etc/yggdrasil.conf > /dev/null
      args:
        warn: false
      when: not (config_state is changed)
    - name: '[Yggdrasil] Rename interface'
      replace:
        path: /etc/privoxy/config
        regexp: 'IfName: auto'
        replace: 'IfName: ygg'
      when: not (config_state is changed)
    - name: '[Yggdrasil] Enable and start service'
      systemd:
        name: yggdrasil
        enabled: yes
        state: restarted

  - block: # Firewall
    - name: '[Firewall] Prevent incoming traffic'
      ufw:
        state: enabled
        rule: deny
        interface_in: ygg

  - block: # Privoxy
    - name: '[Privoxy] Install and set up for https://github.com/perguth/yggdrasil-chromeos'
      apt: update_cache=yes state=present name=privoxy
    - name: '[Privoxy] Change port to :8008'
      replace:
        path: /etc/privoxy/config
        regexp: '8118'
        replace: '8008'
    - name: '[Privoxy] Restart service'
      systemd:
        name: privoxy
        state: restarted
