---

- name: 'Installing'
  hosts: localhost
  connection: local

  become: true
  tasks:

  - block: # Yggdrasil Network
    - name: Get DEB architecture
      shell: dpkg --print-architecture
      register: deb_architecture
    - name: Download Yggstack
      get_url:
        url: "https://github.com/yggdrasil-network/yggstack/releases/latest/download/yggstack-linux-{{ deb_architecture.stdout }}-static"
        dest: /usr/local/bin/yggstack
        mode: u=rwx,g=rx,o=rx
    - name: See if the config file exists
      stat:
        path: /etc/yggdrasil/yggdrasil.conf
      register: config_exists
    - name: Create the config file
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        mode: u=rwx,g=rx,o=
      loop:
        - { path: /etc/yggdrasil, state: directory }
        - { path: /etc/yggdrasil/yggdrasil.conf, state: touch }
      when: not config_exists.stat.exists
    - name: Generate config
      shell: /usr/local/bin/yggstack -genconf > /etc/yggdrasil/yggdrasil.conf
      when: not config_exists.stat.exists
    - name: Add uplink
      replace:
        path: /etc/yggdrasil/yggdrasil.conf
        regexp: 'Peers: \[\]'
        replace: |-
          Peers: [
            tls://ygg-uplink.thingylabs.io:443
          ]
      when: not config_exists.stat.exists

  - block: # Install systemd service
    - name: 'Create systemd service file'
      copy:
        force: true
        src: yggstack.service
        dest: /etc/systemd/system/yggstack.service
    - name: 'Enable and start service'
      systemd:
        name: yggstack
        daemon_reload: true
        enabled: true
        state: started
